name = "PointInHullVerified"
version = "0.1.0"
defaultTargets = ["PointInHullVerified"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
version = "git#master"

[[lean_lib]]
name = "PointInHullVerified"
